baseURL = 'https://lactoseintolerant.dev/'
languageCode = 'en-us'
theme = "archie"
title = 'lactose intolerant'

# Code Highlight
paginate = 3 # articles per page
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "monokai"

[params]
customcss = [ "css/index.css" ]
katex = true # enable KaTeX support
mathjax = true # enable MathJax support
mode = "light" # color-mode → light,dark,toggle or auto
subtitle = "This is where I post my random thoughts or things that I want to share."
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags

[[params.social]]
icon = "github"
name = "gitHub"
url = "https://github.com/kariy/blog"

[[params.social]]
icon = "twitter"
name = "x"
url = "https://x.com/ammarif_/"

# Main menu Items

[[menu.main]]
name = "about"
url = "/about"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3
